apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-rd
  namespace: kube-system
  labels:
    k8s-app: fluentd-rd
    version: v2.0.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-rd
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd-rd
      serviceAccountName: fluentd-rd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: robertvilvert/fluentd:2.10.17
        env:
          -
            name: TOKEN
            valueFrom:
              secretKeyRef:
                name: logentries
                key: TOKEN
          -
            name: CA_CERT
            valueFrom:
              secretKeyRef:
                name: fluentd-rd-secret
                key: ca.crt
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      tolerations:
          #- operator: "Exists"
          - effect: "NoSchedule"
            key: "node-role.kubernetes.io/master"
