apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-rd
  namespace: kube-system
  labels:
    k8s-app: fluentd-rd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: v1
kind: Secret
metadata:
  name: fluentd-rd-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: fluentd-rd
type: kubernetes.io/service-account-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-rd
  labels:
    k8s-app: fluentd-rd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "secrets"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-rd
  labels:
    k8s-app: fluentd-rd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-rd
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-rd
  apiGroup: rbac.authorization.k8s.io
---
